version: "3.6"

services:
  web:
    build: ./web/
    ports:
      - "8080:8080"
    volumes:
      - ./web/src:/app/src
      - ./web/yarn.lock:/app/yarn.lock
      - ./web/package.json:/app/package.json
    command: yarn start
    environment:
      - API_URL=http://localhost:3000
